### ISSUE TITLE
feat(models): 训练并支持规则包网站的语言模型

### ISSUE THREAD

**Issue by HsiangNianian** [HydroRoll-Team/infini#18]
训练离线语言模型，初步完成用户对规则书词条的查询需求，并内置在规则书网站中，同时给出本地开放使用的api接口，供骰子的`.wiki`命令调用。

**Comment by HsiangNianian** [comment]
简子姐好帅

**Comment by HsiangNianian** [comment]
> 简子姐好帅

说的好！

**Comment by HsiangNianian** [comment]
> 简子姐好帅

说的好！

**Comment by HsiangNianian** [comment]
1

**Comment by HsiangNianian** [comment]
2

**Comment by HsiangNianian** [comment]
3

**Comment by HsiangNianian** [comment]
4

**Comment by HsiangNianian** [comment]
5

**Comment by HsiangNianian** [comment]
6

**Comment by HsiangNianian** [comment]
3

**Comment by HsiangNianian** [comment]
> > 简子姐好帅
> 
> 说的好！

中肯的

**Comment by HsiangNianian** [comment]
> > > 简子姐好帅
> > 
> > 
> > 说的好！
> 
> 中肯的

色色sensei, suki suki daisuki

**Comment by HsiangNianian** [comment]
> 色色sensei, suki suki daisuki

1

**Comment by HsiangNianian** [comment]
2

> > 色色sensei, suki suki daisuki
> 
> 1

**Comment by HsiangNianian** [comment]
他说我头像非主流
![image](https://github.com/HydroRoll-Team/HydroRollCore/assets/44714368/297c801e-8371-4e6a-8a82-7a95caf8d991)

**Comment by HsiangNianian** [comment]
LLAMA2

**Comment by HsiangNianian** [comment]
计划采用`huggingface`的`pipeline`与`AutoModelForQuestionAnswering`类对[qa-roberta-base-chinese-extractive](https://huggingface.co/liam168/qa-roberta-base-chinese-extractive)模型封装后，为文档的`md`内容`escape`后作为语料进行训练，预计能够达到基本的询问要求，但是会根据文档（规则书词条）大小整体增加至少400MB的内存。

**Comment by fu050409** [comment]
这个Feature还是比较抽象的

**Comment by fu050409** [comment]
此Feature同样建议在IPM内实现

**Comment by HsiangNianian** [comment]
> 此Feature同样建议在IPM内实现

应当在 infini 实现，然后暴露接口给 ipm 进行指令代理，不应该由 ipm 包含模型的训练功能。

**Comment by fu050409** [comment]
Infini 是轻量的文本输入输出流框架，如果加入模型训练，对 Infini 的架构来说是得不偿失的，模型训练本身是为了规则包的文档而不是规则包本身，这最多只能是 IPM 的一个实验性功能

**Comment by fu050409** [comment]
IPM 生成文档的功能是可以直接从 Infini 调用原始数据的，不应该由 Infini 实现模型训练

**Comment by HsiangNianian** [comment]
ipm 应当只是一个包管理与分发器，不应该具备复杂的训练与推理功能。相反，infini 作为框架，模型的训练与推理代码应当作为其本质上是工具的utils实现，请不要将标准与工具实现混淆。

**Comment by fu050409** [comment]
Infini 应当只是轻量的文本输入输出流框架，它应当只处理文本输入，内容生成，内容分发，如果你希望创建一个具有模型训练能力的规则包，请参考 Infini 文档。或者如果你希望创建一个具有模型训练能力的 CLI 工具包，请实现一个 IPM 插件或创建一个新的项目。

**Comment by HsiangNianian** [comment]
另外，模型的训练和推理，受到规则包词条的数目影响，对于绝大多数规则书而言，推理出40MB左右的轻量检索模型是完全够用的；然而就此功能本身，尤其是作为“水系核心”而言，nlp功能是必须的（但作为规则包标准的实现的课外话，因为infini作为工具，尽管有其必须按照标准来实现的职责，但是，工具也应当具备拓展功能）。

**Comment by HsiangNianian** [comment]
> Infini 应当只是轻量的文本输入输出流框架，它应当只处理文本输入，内容生成，内容分发，如果你希望创建一个具有模型训练能力的规则包，请参考 Infini 文档。或者如果你希望创建一个具有模型训练能力的 CLI 工具包，请实现一个 IPM 插件或创建一个新的项目。

？
